FROM gradle:8.10.2-jdk17 AS build
WORKDIR /app
COPY . .
RUN gradle :execution-service:bootJar --no-daemon

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/execution-service/build/libs/*.jar app.jar
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
