rootProject.name = 'v1'

include 'kafka-platform'
include 'resilience-platform'
include 'workflow-service'
include 'execution-service'
include 'monitoring-service'
include 'frontend-service'
include 'gateway-service'
include 'trigger-service'
include 'notify-service'
include 'bff-service'
include 'dlq-processor-service'
include 'discovery-service'
