spring.application.name=frontend-service
server.port=8088
workflow.service.base-url=${WORKFLOW_URL:http://localhost:8081}
execution.service.base-url=${EXECUTION_URL:http://localhost:8082}
monitoring.service.base-url=${MONITORING_URL:http://localhost:8083}

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.configs.default.slidingWindowSize=20
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.workflowApi.baseConfig=default
resilience4j.circuitbreaker.instances.executionApi.baseConfig=default
resilience4j.circuitbreaker.instances.monitoringApi.baseConfig=default
