spring.application.name=monitoring-service
server.port=8083
workflow.service.base-url=${WORKFLOW_URL:http://localhost:8081}
execution.service.base-url=${EXECUTION_URL:http://localhost:8082}
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
app.kafka.partitions=${KAFKA_TOPIC_PARTITIONS:6}
app.kafka.replication-factor=${KAFKA_TOPIC_REPLICATION_FACTOR:1}
spring.kafka.consumer.properties.isolation.level=read_committed
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/workflow_monitoring}
management.endpoints.web.exposure.include=health,info,prometheus

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

resilience4j.circuitbreaker.configs.default.slidingWindowSize=20
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=30s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.workflowApi.baseConfig=default
resilience4j.circuitbreaker.instances.executionApi.baseConfig=default
