spring.application.name=notify-service
server.port=8085
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP:localhost:9092}
app.kafka.partitions=${KAFKA_TOPIC_PARTITIONS:6}
app.kafka.replication-factor=${KAFKA_TOPIC_REPLICATION_FACTOR:1}
spring.kafka.consumer.properties.isolation.level=read_committed
spring.elasticsearch.uris=${ELASTIC_URL:http://elasticsearch:9200}
management.endpoints.web.exposure.include=health,info,prometheus

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
