plugins {
    id 'java-library'
}

dependencies {
    api platform('org.springframework.boot:spring-boot-dependencies:3.3.5')
    api 'org.springframework.boot:spring-boot-starter-aop'
    api 'io.github.resilience4j:resilience4j-spring-boot3:2.2.0'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
